version: '3.8'

services:
  # Agentic Mentor Application
  agentic-mentor:
    build: .
    ports:
      - "3000:3000"
    environment:
      - WEB_HOST=0.0.0.0
      - WEB_PORT=3000
      - WEB_DEBUG=false
      - REDIS_URL=redis://redis:6379
      - CHROMA_PERSIST_DIRECTORY=./data/chroma
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - agentic-network

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - agentic-network

  # Optional: PostgreSQL for advanced analytics
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=agentic_mentor
      - POSTGRES_USER=agentic
      - POSTGRES_PASSWORD=secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - agentic-network

  # Optional: Nginx for production deployment
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - agentic-mentor
    restart: unless-stopped
    networks:
      - agentic-network

volumes:
  redis_data:
  postgres_data:

networks:
  agentic-network:
    driver: bridge 